### ISSUE TITLE
Hover popup

### ISSUE THREAD

**Issue by CLCmatmcmahon** [cheltenhamladiescollege/helpdesk#10]
Works want to be able to however over an item and see more details about the item.  Some of this requirement may be because of a large list of helpdesk calls and no ability to go back once you have opened a call.

**Comment by CLCmatmcmahon** [comment]
Fix this issue by fixing the back button

**Comment by atomicjam** [comment]
this is no longer a requirement as back button now works added to new helpdesk, due for easter launch.
