### ISSUE TITLE
closed ticket report

### ISSUE THREAD

**Issue by CLClangleyg** [cheltenhamladiescollege/helpdesk#167]
Report shows a list of closed calls. However it shows the name of the engineer that the call was assigned to, not the engineer who closed it.

Reported by AR

Report may also be using assigned engineer for  sql instead of closing engineer

/manager/report/closed/

**Comment by atomicjam** [comment]
added to digital development plan trying to keep all development work in once place on a kaban board

https://tasks.office.com/cheltladiescollege.org/en-gb/Home/PlanViews/PXdW-XIH1UeCyvjkwO8Hn5YADDPl
