### ISSUE TITLE
Support hours coverage sheet

### ISSUE THREAD

**Issue by CLCmatmcmahon** [cheltenhamladiescollege/helpdesk#20]
At present the system has a very basic day table which shows who is in on which days on a normal week.  This allows auto-allocation of jobs.  This would allow users to update their own hours and the system could then use this detail to allocate jobs in a more intelligent way.

**Comment by atomicjam** [comment]
need further thought to be practical while flexible and should not be IT only needs to be usable for all helpdesks, so research on other departments hours needs to be done

**Comment by atomicjam** [comment]
not to be developed
