### ISSUE TITLE
Asset Management system

### ISSUE THREAD

**Issue by CLCmatmcmahon** [cheltenhamladiescollege/helpdesk#21]
Do we want to build asset management into to the helpdesk.  The benefits are:

can track assets and the time we are spending dealing them
we can get historic views of what has happened in the past 
etc...

**Comment by atomicjam** [comment]
system no longer needs to be an asset management system but should be able to pull details from our existing system using the api

**Comment by atomicjam** [comment]
new asset management system to be used instead
