### ISSUE TITLE
Multiple engineers to work on 1 ticket

### ISSUE THREAD

**Issue by CLCmatmcmahon** [cheltenhamladiescollege/helpdesk#4]
Helpdesks are currently assigned to 1 person only.  Sometimes 2 people or more are required for the job and we need to break this down - example is a job which requires a ladder at height which then needs a second person to hold the ladder ?  Do we add two calls or do we collect this information at the end of the call when it is closed.

**Comment by atomicjam** [comment]
won't develop fixed in other issues
