### ISSUE TITLE
Ticket stage report

### ISSUE THREAD

**Issue by CLCmatmcmahon** [cheltenhamladiescollege/helpdesk#8]
Managers report to show average for each stage of their heldpesk.  So example how long on average for the call to be assigned, how long for first update, how long until close. Was this escalated and how long was it before response.  This could be used by other departments.

**Comment by atomicjam** [comment]
![img_0036](https://cloud.githubusercontent.com/assets/5812359/14671894/517b7f74-06ec-11e6-8ce6-6f86ea7e4be0.jpg)

**Comment by atomicjam** [comment]
this wont be possible without splitting ticket details out from existing single field into more sensible relational table. but this is a much bigger task I will log as a new issue
